<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ErrorManager" Id="{842a81e2-e336-475a-838f-6e9c58939475}" SpecialFunc="None">
    <Declaration><![CDATA[// This class is for interfacing with the EventLogger class
FUNCTION_BLOCK ErrorManager
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>