<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ErrorManager_t" Id="{842a81e2-e336-475a-838f-6e9c58939475}" SpecialFunc="None">
    <Declaration><![CDATA[// This class is for managing all error detecting systems and is regestring errors in diffrent error classes
FUNCTION_BLOCK ErrorManager_t
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>