<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ARCommunication_t" Id="{3697f1d2-5144-45fb-a78b-bb7912cd4429}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ARCommunication_t
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	_ARDevice : FB_IotWebSocketClient;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>